In [1]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/restaurant_inspections.csv.gz",
    parse_dates=["INSP_DATE"],
    low_memory=False
)

print(df.shape)

(681641, 144)

In [2]:
df["LICENSE_NO"].nunique()

86492

In [3]:
(
    df.groupby(
        ["LICENSE_NO", "DBA_NAME", "LOC_ADDRESS"]
    )
    .size()
    .sort_values(ascending=False)
    .head(25)
)

LICENSE_NO  DBA_NAME                        LOC_ADDRESS
1102633     MOM'S OG                        1017 W UNIVERSITY AVE                            65
6217228     LITTLE INDIA                    25000 US HWY 19 N                                51
7405560     CHINA MASTER                    1700 W INTERNATIONAL SPEEDWAY BLVD, SUITE 148    48
6217167     SANTA FE MEXICAN GRILL          800 CLEARWATER LARGO RD                          43
2613020     CASA DORA ITALIAN CAFE          108 E FORSYTH ST                                 42
6011515     BLUE ANCHOR                     804 E ATLANTIC AVE                               41
1101752     MR HAN RESTAURANT               6944 NW 10 PL                                    40
7407198     THE PARCHED OAK                 145 N WOODLAND BLVD                              39
2613945     LA NOPALERA MEXICAN RESTAURANT  8206 PHILIPS HWY STE 29                          38
2334107     IRON SUSHI                      9030 SW 72 PL                                    38
1305382     CHOW TIME GRILL & BUFFET        2345 MARTIN LUTHER KING BLVD                     38
5900962     LITTLE ITALY                    2901 B-1 PARKWAY BLVD.                           37
3917858     WINGHOUSE BAR AND GRILL         3712 W  COLUMBUS DR                              37
7407565     PONCHO'S TACOS & ICE CREAM      201 SEABREEZE BLVD                               36
2612750     CASA MARINA HOTEL & RESTAURANT  691 N 1 ST                                       36
3801116     CANG TONG                       110 SEBRING SQUARE                               34
5813862     SUGAR FACTORY                   8371 INTERNATIONAL DR STE 70                     34
1103408     ZEN NOODLES BAR                 3117 SW 34TH ST STE 2                            34
6102458     SKINNYS BAR & GRILL             13228 US HWY 19                                  33
6102761     GREEN TEA                       11832 US HWY 19                                  33
7403361     THE GRILLE AT RIVERVIEW         101 FLAGLER AVE                                  33
6903870     KOY WAN HIBACHI BUFFET          945 W SR 436 #1179                               33
1900126     CITRUS SPGS GOLF&COUNTRY CLUB   8690 N GOLF VIEW DR                              33
7405539     IRON AXE BAR & GRILL, INC.      2842 S RIDGEWOOD AVE                             32
6217123     DISCOVERY INDIAN CUISINE        38593  US 19 STE 300                             32
dtype: int64

In [4]:
(
    df.groupby(
        ["LICENSE_NO", "DBA_NAME", "LOC_ADDRESS"]
    )["HIGH_VIOL"]
    .sum()
    .sort_values(ascending=False)
    .head(25)
)

LICENSE_NO  DBA_NAME                             LOC_ADDRESS
6213109     NAME VIET BISTRO MACHI               8150 N 49 ST                                     161.0
7403361     THE GRILLE AT RIVERVIEW              101 FLAGLER AVE                                  142.0
2613020     CASA DORA ITALIAN CAFE               108 E FORSYTH ST                                 122.0
6217167     SANTA FE MEXICAN GRILL               800 CLEARWATER LARGO RD                          122.0
6217228     LITTLE INDIA                         25000 US HWY 19 N                                114.0
6019913     LA GRANJA RESTAURANT                 10590 W FOREST HILL BLVD                         112.0
6021961     LEMONGRASS ASIAN BISTRO              10312 FOREST HILL BLVD STE 204                   104.0
2612750     CASA MARINA HOTEL & RESTAURANT       691 N 1 ST                                       103.0
2652482     MIS DELICIAS LATINAS                 4241 UNIVERSITY BLVD S                           103.0
2613836     MAA KITCHEN                          8206 PHILLIPS HWY ST 25                          102.0
7407565     PONCHO'S TACOS & ICE CREAM           201 SEABREEZE BLVD                               101.0
7405560     CHINA MASTER                         1700 W INTERNATIONAL SPEEDWAY BLVD, SUITE 148     98.0
5301302     MIKATA BUFFET INC                    3201 NW FEDERAL HWY 1                             97.0
2652281     MARIA GUADALUPE GUTIERREZ            10014 ATLANTIC BLVD                               96.0
1102633     MOM'S OG                             1017 W UNIVERSITY AVE                             95.0
6011515     BLUE ANCHOR                          804 E ATLANTIC AVE                                95.0
7406811     PHO SAIGON VIETNAMESE RESTAURANT     312 S PENINSULA DR                                92.0
1103692     LAS CARRETAS MEXICAN RESTAURANT      3501 SW 2 AVE                                     91.0
7407175     EL MOLCAJETE COCINA MEXICANA         2976 S RIDGEWOOD AVE                              90.0
1103346     TUPTIM THAI RESTAURANT & SUSHI BAR   1228 W UNIVERSITY AVE                             89.0
5810470     CHINA LEE                            2338 S KIRKMAN RD                                 89.0
6217840     UMAMI ENDLESS SUSHI & BAR LLC        3942 TYRONE BLVD N STE D                          89.0
6214063     HALONG BAY VIETNAMESE CUISINE        5944 34 ST N. STE 39-43                           88.0
7407405     ROYAL SUSHI GRILL AND THAI           1816 S RIDGEWOOD AVE                              85.0
6011842     PINOLANDIA - FRITANGA & TORTILLERIA  1290 N MILITARY TRL                               84.0
Name: HIGH_VIOL, dtype: float64

In [5]:
summary = (
    df.groupby(
        ["LICENSE_NO", "DBA_NAME", "LOC_ADDRESS"]
    )
    .agg(
        inspections=("INSP_NO", "count"),
        high_priority=("HIGH_VIOL", "sum")
    )
)

summary["per_inspection"] = (
    summary["high_priority"]
    / summary["inspections"]
)

summary[
    summary["inspections"] >= 5
].sort_values(
    "per_inspection",
    ascending=False
).head(25)

,,,inspections,high_priority,per_inspection
LICENSE_NO,DBA_NAME,LOC_ADDRESS,,,
5911115,MAIN GATE FLEA MARKET FOOD COURT #1,5407 W IRLO BRONSON MEMORIAL HWY,10,72.0,7.200000
2652281,MARIA GUADALUPE GUTIERREZ,10014 ATLANTIC BLVD,14,96.0,6.857143
6012682,SUSHI YAMI,6177 JOG RD,5,34.0,6.800000
5815344,HABIBI LEBANESE GRILL,8001 S ORANGE BLOSSOM RD STE 1510,5,33.0,6.600000
6213109,NAME VIET BISTRO MACHI,8150 N 49 ST,26,161.0,6.192308
7406995,DON PEPPER'S MEXICAN GRILL & CANTINA,794 S ATLANTIC AVE,7,42.0,6.000000
6009906,POPPIES RESTAURANT & DELI,4900 LINTON BLVD,8,46.0,5.750000
2614216,WILD WING CAFE,4555 SOUTHSIDE BLVD,5,28.0,5.600000
6019135,SUSHI YAMA,10260 FOREST HILL BLVD,9,49.0,5.444444
6006078,RIVALES TAQUERIA AND CRAFT BAR,11924 W FOREST HILL BLVD STE 28,8,43.0,5.375000
6020058,PEPPERMINT THAI,11328 OKEECHOBEE BLVD,13,69.0,5.307692
2613115,JAX FISH SHRIMP AND CHICKEN,3646 BLANDING BLVD,7,37.0,5.285714
6217769,CAFE BICH NGA,5572 PARK BLVD,9,46.0,5.111111
6013433,KING'S SUPER BUFFET,4270 OKEECHOBEE BLVD,12,61.0,5.083333
7100354,MCALPIN KOUNTRY KITCHEN,9929 170 TERR STE 101,5,25.0,5.000000
6213109,LOON FONG RESTAURANT,8150 N 49 STREET,13,64.0,4.923077
6215246,DAVE'S DINER,1479 BELCHER RD UNIT Y-Z,9,44.0,4.888889
6502067,SUMO SUSHI,107 NATURE WALK PKWY STE 109,7,34.0,4.857143
6019285,CHINA SKY,7040 SEMINOLE PRATT WHITNEY RD,12,58.0,4.833333
6022880,MOTEK BOCA,5377 TOWN CENTER RD #300,5,24.0,4.800000
5813948,THE CRAZY COCONUT,5406 HANSEL AVE,11,52.0,4.727273
6020992,REAL WOK,4640 HYPOLUXO RD STE 5,7,33.0,4.714286
5911141,SLICE OF NY,1042 CYPRESS PKWY,9,42.0,4.666667
7406365,CHINA HOUSE 168 INC,1844 RIDGEWOOD AVE,17,79.0,4.647059
5815515,YH SEAFOOD CLUBHOUSE,8081 TURKEY LAKE RD STE 700,16,74.0,4.625000

In [6]:
restaurant_summary = (
    df.groupby(
        ["LICENSE_NO", "DBA_NAME", "LOC_ADDRESS", "LOC_CITY"]
    )
    .agg(
        inspections=("INSP_NO", "count"),
        high_priority=("HIGH_VIOL", "sum"),
        total_violations=("VIOLATIONS", "sum")
    )
    .reset_index()
)

restaurant_summary["high_priority_per_inspection"] = (
    restaurant_summary["high_priority"]
    / restaurant_summary["inspections"]
)

restaurant_summary["total_violations_per_inspection"] = (
    restaurant_summary["total_violations"]
    / restaurant_summary["inspections"]
)

restaurant_summary = restaurant_summary[
    restaurant_summary["inspections"] >= 10
]

restaurant_summary.sort_values(
    "high_priority_per_inspection",
    ascending=False
).head(30)

,LICENSE_NO,DBA_NAME,LOC_ADDRESS,LOC_CITY,inspections,high_priority,total_violations,high_priority_per_inspection,total_violations_per_inspection
80600,5911115,MAIN GATE FLEA MARKET FOOD COURT #1,5407 W IRLO BRONSON MEMORIAL HWY,KISSIMMEE,10,72.0,227,7.200000,22.700000
40070,2652281,MARIA GUADALUPE GUTIERREZ,10014 ATLANTIC BLVD,JACKSONVILLE,14,96.0,104,6.857143,7.428571
91740,6213109,NAME VIET BISTRO MACHI,8150 N 49 ST,PINELLAS PARK,26,161.0,560,6.192308,21.538462
84807,6020058,PEPPERMINT THAI,11328 OKEECHOBEE BLVD,ROYAL PALM BEACH,13,69.0,164,5.307692,12.615385
83722,6013433,KING'S SUPER BUFFET,4270 OKEECHOBEE BLVD,WEST PALM BEACH,12,61.0,104,5.083333,8.666667
91739,6213109,LOON FONG RESTAURANT,8150 N 49 STREET,PINELLAS PARK,13,64.0,266,4.923077,20.461538
84395,6019285,CHINA SKY,7040 SEMINOLE PRATT WHITNEY RD,LOXAHATCHEE,12,58.0,105,4.833333,8.750000
74440,5813948,THE CRAZY COCONUT,5406 HANSEL AVE,ORLANDO,11,52.0,256,4.727273,23.272727
108698,7406365,CHINA HOUSE 168 INC,1844 RIDGEWOOD AVE,HOLLY HILL,17,79.0,306,4.647059,18.000000
76214,5815515,YH SEAFOOD CLUBHOUSE,8081 TURKEY LAKE RD STE 700,ORLANDO,16,74.0,353,4.625000,22.062500
24928,2332845,SUVI THAI & SUSHI RESTAURANT,250 N. HOMESTEAD BLVD.,HOMESTEAD,10,46.0,164,4.600000,16.400000
105704,6903982,MEXICAN RESTAURANT LOS MONDRAGON,2960 W SR.426 # 1000,OVIEDO,10,46.0,127,4.600000,12.700000
38540,2615633,J & C CRAB,1036-24 DUNN AVE,JACKSONVILLE,14,64.0,197,4.571429,14.071429
80864,5911475,ROUTE 66 ROADHOUSE,8520 WEST IRLO BRONSON MEMORIAL HWY,KISSIMMEE,16,73.0,391,4.562500,24.437500
40319,2652482,MIS DELICIAS LATINAS,4241 UNIVERSITY BLVD S,JACKSONVILLE,23,103.0,195,4.478261,8.478261
84718,6019908,TOREROS MEXICAN RESTAURANT,911 VILLAGE BLVD STE #801,WEST PALM BEACH,16,71.0,157,4.437500,9.812500
108892,7406501,WOK 'N ROLL,1345 W GRANDA BLVD #8,ORMOND BEACH,15,66.0,282,4.400000,18.800000
85070,6020487,WAH LAN CHINESE RESTAURANT,989 S MAIN ST,BELLE GLADE,13,57.0,91,4.384615,7.000000
54821,4508813,ROOT & BRANCH BISTRO & BAR,1200 OAKLEY SEAVER DR STE 102 & 104,CLERMONT,11,48.0,185,4.363636,16.818182
64742,5203191,CHINA LEE BUFFET,3933 E SILVER SPRINGS BLVD,OCALA,17,74.0,253,4.352941,14.882353
86364,6021961,LEMONGRASS ASIAN BISTRO,10312 FOREST HILL BLVD STE 204,WELLINGTON,24,104.0,146,4.333333,6.083333
38835,2615942,ANEJO COCINA MEXICANA,220 RIVERSIDE AVE SUITE 101,JACKSONVILLE,15,65.0,207,4.333333,13.800000
84723,6019913,LA GRANJA RESTAURANT,10590 W FOREST HILL BLVD,WELLINGTON,26,112.0,206,4.307692,7.923077
20176,2318389,SOUTH GARDEN CHINESE RESTAURANT,10855 SW 72 ST UNIT 10,MIAMI,13,56.0,275,4.307692,21.153846
108160,7403361,THE GRILLE AT RIVERVIEW,101 FLAGLER AVE,NEW SMYRNA BCH,33,142.0,398,4.303030,12.060606
36285,2612400,CHINA BUFFET,6001 ARGYLE FOREST BVLD STE 32,JACKSONVILLE,10,43.0,159,4.300000,15.900000
83551,6012903,CRAZY BUFFET,2030 PALM BEACH LAKES BLVD,WEST PALM BEACH,17,73.0,113,4.294118,6.647059
28387,2336597,LA BRASA KENDALL,10855 SW 72 ST UNIT 60,MIAMI,11,47.0,236,4.272727,21.454545
109470,7407405,ROYAL SUSHI GRILL AND THAI,1816 S RIDGEWOOD AVE,EDGEWATER,20,85.0,296,4.250000,14.800000
19826,2315937,CHORIPAN CAFETERIA,4546 SW 74 AVE,MIAMI,10,42.0,165,4.200000,16.500000

In [7]:
(
    df.groupby("INSPTYPE")
      .agg(
          inspections=("INSP_NO", "count"),
          avg_high_priority=("HIGH_VIOL", "mean"),
          avg_total=("VIOLATIONS", "mean")
      )
      .sort_values("avg_high_priority", ascending=False)
)

                           inspections  avg_high_priority  avg_total
INSPTYPE
Complaint Full                   55960           1.305642   6.352823
Routine - Food                  567371           1.010604   5.210765
Complaint Partial                 7398           0.418120   1.637470
Food-Licensing Inspection        50859           0.264286   1.713168
Routine - Lodging                   25           0.080000   0.560000
Disaster Response                   28           0.000000   0.392857

In [8]:
most_inspected = (
    df.groupby(
        ["LICENSE_NO", "DBA_NAME", "LOC_ADDRESS"]
    )
    .size()
    .sort_values(ascending=False)
)

most_inspected.head(10)

LICENSE_NO  DBA_NAME                        LOC_ADDRESS
1102633     MOM'S OG                        1017 W UNIVERSITY AVE                            65
6217228     LITTLE INDIA                    25000 US HWY 19 N                                51
7405560     CHINA MASTER                    1700 W INTERNATIONAL SPEEDWAY BLVD, SUITE 148    48
6217167     SANTA FE MEXICAN GRILL          800 CLEARWATER LARGO RD                          43
2613020     CASA DORA ITALIAN CAFE          108 E FORSYTH ST                                 42
6011515     BLUE ANCHOR                     804 E ATLANTIC AVE                               41
1101752     MR HAN RESTAURANT               6944 NW 10 PL                                    40
7407198     THE PARCHED OAK                 145 N WOODLAND BLVD                              39
2613945     LA NOPALERA MEXICAN RESTAURANT  8206 PHILIPS HWY STE 29                          38
2334107     IRON SUSHI                      9030 SW 72 PL                                    38
dtype: int64

In [9]:
restaurant = df[df["LICENSE_NO"] == 1102633]

restaurant = restaurant[
    [
        "INSP_DATE",
        "INSPTYPE",
        "DISPOSITION",
        "HIGH_VIOL",
        "VIOLATIONS"
    ]
].sort_values("INSP_DATE")

restaurant

,INSP_DATE,INSPTYPE,DISPOSITION,HIGH_VIOL,VIOLATIONS
59522,2021-07-23,Routine - Food,Administrative complaint recommended,5.0,23
58788,2021-07-26,Routine - Food,Call Back - Complied,0.0,0
40684,2021-09-09,Complaint Full,Administrative complaint recommended,7.0,26
39985,2021-09-10,Complaint Full,"Call Back - Extension given, pending",0.0,1
14113,2021-11-16,Complaint Full,Call Back - Admin. complaint recommended,0.0,1
...,...,...,...,...,...
619572,2026-06-17,Complaint Full,Call Back - Admin. complaint recommended,4.0,6
618128,2026-06-23,Complaint Full,Call Back - Admin. complaint recommended,1.0,3
618256,2026-06-23,Routine - Food,Emergency order recommended,1.0,1
617812,2026-06-24,Routine - Food,Emergency Order Callback Not Complied,1.0,1
617860,2026-06-24,Routine - Food,Emergency Order Callback Complied,0.0,0

In [10]:
(
    df.groupby("INSPTYPE")
      .agg(
          inspections=("INSP_NO", "count"),
          failed=("DISPOSITION", lambda x: x.str.contains("Admin|Complaint", case=False, na=False).sum())
      )
      .assign(failure_rate=lambda x: x["failed"] / x["inspections"])
      .sort_values("failure_rate", ascending=False)
)

                           inspections  failed  failure_rate
INSPTYPE
Complaint Full                   55960    6778      0.121122
Routine - Food                  567371   48292      0.085115
Complaint Partial                 7398     558      0.075426
Food-Licensing Inspection        50859     406      0.007983
Disaster Response                   28       0      0.000000
Routine - Lodging                   25       0      0.000000

In [11]:
(
    df[df["INSPTYPE"].str.contains("Complaint", na=False)]
    ["DISPOSITION"]
    .value_counts()
)

DISPOSITION
Inspection Completed - No Further Action    29058
Call Back - Complied                        10978
Warning Issued                               9062
Administrative complaint recommended         5022
Call Back - Admin. complaint recommended     2289
Emergency order recommended                  2044
Call Back - Extension given, pending         2008
Emergency Order Callback Complied            1527
Emergency Order Callback Not Complied         960
Emergency Order Callback Time Extension       311
Assigned to Inspector                          54
Administrative determination recommended       14
Not available electronically                   12
Admin. Complaint Callback Complied              8
Insp. Completed - Warning Given, Pending        5
Admin. Complaint Callback Not Complied          3
Allegation Not Observed                         3
Name: count, dtype: int64

In [12]:
(
    df.groupby("CNTY_DESC")
      .agg(
          inspections=("INSP_NO", "count"),
          avg_high=("HIGH_VIOL", "mean")
      )
      .query("inspections >= 500")
      .sort_values("avg_high", ascending=False)
      .head(20)
)

            inspections  avg_high
CNTY_DESC
Baker               560  1.514286
Levy               1299  1.434950
Volusia           19698  1.384240
Martin             6300  1.376825
Palm Beach        46906  1.340511
Duval             35353  1.309681
Putnam             1952  1.296258
Clay               4658  1.295620
Bradford            617  1.277147
Flagler            3496  1.270100
Marion             9276  1.211514
St. Johns         10588  1.205610
Alachua            8998  1.194509
Pinellas          34106  1.178632
Hardee              544  1.167279
Nassau             3038  1.159645
Suwannee            955  1.149738
Lake               9646  1.105536
Broward           60813  1.052742
Seminole          12601  1.042864

In [13]:
inspection_type_counts = (
    df["INSPTYPE"]
    .value_counts(dropna=False)
    .rename_axis("inspection_type")
    .reset_index(name="inspections")
)

inspection_type_counts["percent"] = (
    inspection_type_counts["inspections"]
    / inspection_type_counts["inspections"].sum()
    * 100
)

inspection_type_counts

             inspection_type  inspections    percent
0             Routine - Food       567371  83.236044
1             Complaint Full        55960   8.209600
2  Food-Licensing Inspection        50859   7.461259
3          Complaint Partial         7398   1.085322
4          Disaster Response           28   0.004108
5          Routine - Lodging           25   0.003668

In [14]:
complaints = df[
    df["INSPTYPE"].isin(
        ["Complaint Full", "Complaint Partial"]
    )
].copy()

print("Complaint inspections:", len(complaints))

Complaint inspections: 63358

In [15]:
complaint_findings = pd.Series({
    "Zero high-priority violations":
        (complaints["HIGH_VIOL"] == 0).mean() * 100,

    "At least one high-priority violation":
        (complaints["HIGH_VIOL"] >= 1).mean() * 100,

    "Three or more high-priority violations":
        (complaints["HIGH_VIOL"] >= 3).mean() * 100
})

complaint_findings.round(1)

Zero high-priority violations             47.8
At least one high-priority violation      52.1
Three or more high-priority violations    17.0
dtype: float64

In [16]:
complaints["DISPOSITION"].value_counts(dropna=False)

DISPOSITION
Inspection Completed - No Further Action    29058
Call Back - Complied                        10978
Warning Issued                               9062
Administrative complaint recommended         5022
Call Back - Admin. complaint recommended     2289
Emergency order recommended                  2044
Call Back - Extension given, pending         2008
Emergency Order Callback Complied            1527
Emergency Order Callback Not Complied         960
Emergency Order Callback Time Extension       311
Assigned to Inspector                          54
Administrative determination recommended       14
Not available electronically                   12
Admin. Complaint Callback Complied              8
Insp. Completed - Warning Given, Pending        5
Admin. Complaint Callback Not Complied          3
Allegation Not Observed                         3
Name: count, dtype: int64

In [17]:
complaint_outcomes = (
    complaints["DISPOSITION"]
    .value_counts(dropna=False)
    .rename_axis("outcome")
    .reset_index(name="inspections")
)

complaint_outcomes["percent"] = (
    complaint_outcomes["inspections"]
    / complaint_outcomes["inspections"].sum()
    * 100
)

complaint_outcomes

                                     outcome  inspections    percent
0   Inspection Completed - No Further Action        29058  45.863190
1                       Call Back - Complied        10978  17.326936
2                             Warning Issued         9062  14.302850
3       Administrative complaint recommended         5022   7.926387
4   Call Back - Admin. complaint recommended         2289   3.612803
5                Emergency order recommended         2044   3.226112
6       Call Back - Extension given, pending         2008   3.169292
7          Emergency Order Callback Complied         1527   2.410114
8      Emergency Order Callback Not Complied          960   1.515199
9    Emergency Order Callback Time Extension          311   0.490861
10                     Assigned to Inspector           54   0.085230
11  Administrative determination recommended           14   0.022097
12              Not available electronically           12   0.018940
13        Admin. Complaint Callback Complied            8   0.012627
14  Insp. Completed - Warning Given, Pending            5   0.007892
15    Admin. Complaint Callback Not Complied            3   0.004735
16                   Allegation Not Observed            3   0.004735

In [18]:
complaints_by_year = (
    complaints.groupby("fiscal_year")
    .agg(
        complaint_inspections=("INSP_NO", "count"),
        avg_high_priority=("HIGH_VIOL", "mean"),
        no_high_priority=(
            "HIGH_VIOL",
            lambda x: (x == 0).mean() * 100
        ),
        three_or_more=(
            "HIGH_VIOL",
            lambda x: (x >= 3).mean() * 100
        )
    )
    .reset_index()
)

complaints_by_year.round(2)

,fiscal_year,complaint_inspections,avg_high_priority,no_high_priority,three_or_more
0,2021-22,10874,1.33,42.98,19.38
1,2022-23,12161,1.25,45.07,17.49
2,2023-24,12687,1.22,48.22,17.18
3,2024-25,13368,1.14,50.00,15.99
4,2025-26,14268,1.11,51.35,15.61

In [19]:
comparison = (
    df[df["INSPTYPE"].isin(["Routine - Food", "Complaint Full"])]
    .groupby("INSPTYPE")
    .agg(
        inspections=("INSP_NO", "count"),
        avg_high=("HIGH_VIOL", "mean"),
        zero_high=("HIGH_VIOL", lambda x: (x == 0).mean() * 100),
        three_plus=("HIGH_VIOL", lambda x: (x >= 3).mean() * 100),
        avg_total=("VIOLATIONS", "mean")
    )
    .round(2)
)

comparison

                inspections  avg_high  zero_high  three_plus  avg_total
INSPTYPE
Complaint Full        55960      1.31      44.55       18.84       6.35
Routine - Food       567371      1.01      51.12       13.20       5.21

In [20]:
inspection_type_counts.to_csv(
    "../data/processed/chart_inspection_types.csv",
    index=False
)

In [21]:
comparison.to_csv(
    "../data/processed/chart_routine_vs_complaint.csv"
)

In [22]:
complaint_outcomes.to_csv(
    "../data/processed/chart_complaint_outcomes.csv",
    index=False
)

In [23]:
complaints_by_year.to_csv(
    "../data/processed/chart_complaints_over_time.csv",
    index=False
)

In [24]:
restaurant_counts = (
    df.groupby(["LICENSE_NO", "DBA_NAME"])
      .agg(
          inspections=("INSP_NO", "count"),
          inspection_types=("INSPTYPE", "nunique"),
          dispositions=("DISPOSITION", "nunique")
      )
      .query("inspections >= 15")
      .sort_values(
          ["inspection_types", "dispositions", "inspections"],
          ascending=False
      )
)

restaurant_counts.head(25)

,,inspections,inspection_types,dispositions
LICENSE_NO,DBA_NAME,,,
1102633,MOM'S OG,65,4,10
2613891,INDULGENCE SOUTHERN BISTRO,29,4,10
3100032,LIGHTHOUSE RESTAURANT,29,4,10
6201120,TREASURE ISLAND R BAR,22,4,10
6215207,LOS HERNANDEZ FAMILY RESTAURANT,22,4,10
6501492,SONIC DRIVE IN 4292,21,4,10
7407198,THE PARCHED OAK,39,4,9
3911556,CHINA BUFFET,32,4,9
6217123,DISCOVERY INDIAN CUISINE,32,4,9
5811437,WINGHOUSE BAR AND GRILL,30,4,9
6400773,SONIC DRIVE IN,28,4,9
5810470,CHINA LEE,27,4,9
2616181,SUGAR FACTORY AMERICAN BRASSERIE,26,4,9
6113577,FRANKS RESTAURANT,26,4,9
2001238,ORANGE BUFFET,24,4,9
3912268,THINH AN KITCHEN & TOFU,24,4,9
1400086,FUN POINT,22,4,9
7406883,LA STREGA BISTRO,22,4,9
6500140,SALTWATER COWBOYS,21,4,9
2615527,JIMMY HULAS,20,4,9
7406058,DAISYS DINER,20,4,9
6217842,AROMA INDIAN CUISINE AND BAR,17,4,9
6113390,MULLIGAN'S TAVERN,15,4,9
1901010,PAPA WILLIES BAR AND GRILL,28,4,8
5911797,SICKIES GARAGE BURGERS AND BREWS 1,25,4,8

In [25]:
restaurant = (
    df[df["LICENSE_NO"] == 7407198]
    .sort_values("INSP_DATE")
)

restaurant[
    [
        "INSP_DATE",
        "INSPTYPE",
        "DISPOSITION",
        "HIGH_VIOL",
        "VIOLATIONS"
    ]
]

,INSP_DATE,INSPTYPE,DISPOSITION,HIGH_VIOL,VIOLATIONS
64540,2021-07-13,Complaint Full,Administrative complaint recommended,6.0,10
64220,2021-07-14,Complaint Full,Call Back - Complied,0.0,1
53354,2021-08-09,Complaint Partial,Warning Issued,1.0,1
53209,2021-08-10,Routine - Food,Emergency order recommended,3.0,5
53276,2021-08-10,Complaint Partial,"Call Back - Extension given, pending",1.0,1
52237,2021-08-11,Routine - Food,Emergency Order Callback Complied,0.0,1
52415,2021-08-11,Complaint Partial,Call Back - Complied,0.0,0
16642,2021-11-09,Routine - Food,Emergency order recommended,5.0,19
15910,2021-11-10,Routine - Food,Emergency Order Callback Not Complied,2.0,11
15911,2021-11-10,Routine - Food,Emergency Order Callback Time Extension,0.0,7
107780,2022-03-07,Food-Licensing Inspection,Administrative complaint recommended,3.0,9
106894,2022-03-08,Food-Licensing Inspection,Call Back - Complied,0.0,2
179717,2022-08-18,Routine - Food,Emergency Order Callback Time Extension,0.0,7
179829,2022-08-18,Routine - Food,Emergency order recommended,4.0,15
176607,2022-08-25,Routine - Food,Call Back - Complied,0.0,2
159298,2022-10-17,Routine - Food,Inspection Completed - No Further Action,3.0,13
215181,2023-05-08,Routine - Food,Emergency order recommended,5.0,18
215095,2023-05-08,Routine - Food,Emergency Order Callback Complied,1.0,6
328617,2023-07-10,Routine - Food,Warning Issued,2.0,10
304572,2023-09-11,Routine - Food,Call Back - Complied,0.0,2
371703,2024-03-04,Routine - Food,Emergency order recommended,3.0,14
371302,2024-03-05,Routine - Food,Emergency Order Callback Complied,0.0,2
371303,2024-03-05,Routine - Food,Emergency Order Callback Not Complied,1.0,6
344258,2024-05-03,Routine - Food,Inspection Completed - No Further Action,2.0,8
461598,2024-07-23,Complaint Full,Emergency order recommended,4.0,15
461454,2024-07-24,Complaint Full,Emergency Order Callback Complied,0.0,1
457417,2024-07-31,Complaint Partial,Emergency order recommended,1.0,1
457669,2024-07-31,Complaint Partial,Emergency Order Callback Time Extension,0.0,0
457092,2024-08-01,Complaint Partial,Administrative complaint recommended,1.0,1
457235,2024-08-01,Complaint Partial,"Call Back - Extension given, pending",0.0,0
457339,2024-08-01,Complaint Partial,Call Back - Complied,0.0,0
456744,2024-08-02,Complaint Partial,Call Back - Complied,0.0,0
434003,2024-09-23,Complaint Full,Emergency Order Callback Complied,0.0,4
434247,2024-09-23,Complaint Full,Emergency order recommended,3.0,15
409635,2024-12-02,Routine - Food,Emergency order recommended,4.0,20
408935,2024-12-03,Routine - Food,Emergency Order Callback Complied,0.0,9
524894,2025-02-04,Routine - Food,Inspection Completed - No Further Action,1.0,7
603516,2025-07-31,Routine - Food,Warning Issued,3.0,14
602641,2025-08-01,Routine - Food,Call Back - Complied,1.0,7
589084,2025-09-03,Complaint Full,Administrative complaint recommended,4.0,18
587328,2025-09-05,Complaint Full,Call Back - Complied,0.0,5
565615,2025-10-22,Complaint Full,Emergency order recommended,7.0,22
564494,2025-10-23,Complaint Full,Call Back - Complied,0.0,7
681503,2026-01-05,Routine - Food,Emergency order recommended,5.0,11
680710,2026-01-06,Routine - Food,Emergency Order Callback Time Extension,0.0,6
654214,2026-03-10,Routine - Food,Warning Issued,2.0,10
654406,2026-03-10,Routine - Food,Call Back - Complied,0.0,2
653593,2026-03-11,Routine - Food,Call Back - Complied,0.0,3
617694,2026-06-24,Complaint Full,Inspection Completed - No Further Action,2.0,8

In [26]:
restaurant = (
    df[df["LICENSE_NO"] == 1102633]
    .sort_values("INSP_DATE")
)

restaurant[
    [
        "INSP_DATE",
        "INSPTYPE",
        "DISPOSITION",
        "HIGH_VIOL",
        "VIOLATIONS"
    ]
]

,INSP_DATE,INSPTYPE,DISPOSITION,HIGH_VIOL,VIOLATIONS
59522,2021-07-23,Routine - Food,Administrative complaint recommended,5.0,23
58788,2021-07-26,Routine - Food,Call Back - Complied,0.0,0
40684,2021-09-09,Complaint Full,Administrative complaint recommended,7.0,26
39985,2021-09-10,Complaint Full,"Call Back - Extension given, pending",0.0,1
14113,2021-11-16,Complaint Full,Call Back - Admin. complaint recommended,0.0,1
...,...,...,...,...,...
619572,2026-06-17,Complaint Full,Call Back - Admin. complaint recommended,4.0,6
618128,2026-06-23,Complaint Full,Call Back - Admin. complaint recommended,1.0,3
618256,2026-06-23,Routine - Food,Emergency order recommended,1.0,1
617812,2026-06-24,Routine - Food,Emergency Order Callback Not Complied,1.0,1
617860,2026-06-24,Routine - Food,Emergency Order Callback Complied,0.0,0

In [27]:
chart1 = inspection_type_counts.copy()

# Combine smaller categories
major = [
    "Routine - Food",
    "Complaint Full",
    "Complaint Partial",
    "Food Licensing"
]

chart1["inspection_type"] = chart1["inspection_type"].where(
    chart1["inspection_type"].isin(major),
    "Other"
)

chart1 = (
    chart1.groupby("inspection_type", as_index=False)
          .agg(
              inspections=("inspections", "sum"),
              percent=("percent", "sum")
          )
)

chart1 = chart1.sort_values(
    "inspections",
    ascending=False
)

chart1

     inspection_type  inspections    percent
3     Routine - Food       567371  83.236044
0     Complaint Full        55960   8.209600
2              Other        50912   7.469034
1  Complaint Partial         7398   1.085322

In [28]:
chart1.to_csv(
    "../data/processed/chart1_inspection_types.csv",
    index=False
)

In [29]:
chart2 = comparison.reset_index()

chart2.to_csv(
    "../data/processed/chart2_routine_vs_complaint.csv",
    index=False
)

chart2

         INSPTYPE  inspections  avg_high  zero_high  three_plus  avg_total
0  Complaint Full        55960      1.31      44.55       18.84       6.35
1  Routine - Food       567371      1.01      51.12       13.20       5.21

In [30]:
chart2 = comparison.reset_index()

chart2 = chart2.rename(columns={
    "INSPTYPE": "inspection_type",
    "avg_high": "Average high-priority violations",
    "avg_total": "Average total violations",
    "three_plus": "Inspections with 3+ high-priority violations (%)"
})

chart2

,inspection_type,inspections,Average high-priority violations,zero_high,Inspections with 3+ high-priority violations (%),Average total violations
0,Complaint Full,55960,1.31,44.55,18.84,6.35
1,Routine - Food,567371,1.01,51.12,13.20,5.21

In [31]:
chart2.to_csv(
    "../data/processed/chart2_comparison.csv",
    index=False
)

In [32]:
comparison

                inspections  avg_high  zero_high  three_plus  avg_total
INSPTYPE
Complaint Full        55960      1.31      44.55       18.84       6.35
Routine - Food       567371      1.01      51.12       13.20       5.21

In [33]:
chart2 = comparison.reset_index()

chart2

         INSPTYPE  inspections  avg_high  zero_high  three_plus  avg_total
0  Complaint Full        55960      1.31      44.55       18.84       6.35
1  Routine - Food       567371      1.01      51.12       13.20       5.21

In [34]:
chart2.to_csv(
    "../data/processed/chart2_comparison.csv",
    index=False
)

In [35]:
chart2a = pd.DataFrame({
    "measure": ["Average high-priority violations"],
    "Routine": [
        comparison.loc["Routine - Food", "avg_high"]
    ],
    "Complaint": [
        comparison.loc["Complaint Full", "avg_high"]
    ]
})

chart2a

                            measure  Routine  Complaint
0  Average high-priority violations     1.01       1.31

In [36]:
chart2a.to_csv(
    "../data/processed/chart2a_high_priority.csv",
    index=False
)

In [37]:
chart2b = pd.DataFrame({
    "Type": ["Per inspection"],
    "Routine": [
        comparison.loc["Routine - Food", "avg_total"]
    ],
    "Complaint": [
        comparison.loc["Complaint Full", "avg_total"]
    ]
})

chart2b

             Type  Routine  Complaint
0  Per inspection     5.21       6.35

In [38]:
chart2b.to_csv(
    "../data/processed/chart2b_total_violations.csv",
    index=False
)

In [39]:
chart2c = pd.DataFrame({
    "Type": ["Share of inspections"],
    "Routine": [
        comparison.loc["Routine - Food", "three_plus"]
    ],
    "Complaint": [
        comparison.loc["Complaint Full", "three_plus"]
    ]
})

chart2c

                   Type  Routine  Complaint
0  Share of inspections     13.2      18.84

In [40]:
chart2c.to_csv(
    "../data/processed/chart2c_three_plus.csv",
    index=False
)

In [41]:
chart3 = pd.DataFrame({
    "Result": [
        "No high-priority violations",
        "One or more high-priority violations"
    ],
    "Percent": [
        (complaints["HIGH_VIOL"] == 0).mean() * 100,
        (complaints["HIGH_VIOL"] >= 1).mean() * 100
    ]
})

chart3

                                 Result    Percent
0           No high-priority violations  47.798226
1  One or more high-priority violations  52.126014

In [42]:
chart3.to_csv(
    "../data/processed/chart3_high_priority_results.csv",
    index=False
)

In [43]:
chart4 = (
    complaints["DISPOSITION"]
    .value_counts()
    .rename_axis("Disposition")
    .reset_index(name="Inspections")
)

chart4["Percent"] = (
    chart4["Inspections"]
    / chart4["Inspections"].sum()
    * 100
).round(1)

chart4

                                 Disposition  Inspections  Percent
0   Inspection Completed - No Further Action        29058     45.9
1                       Call Back - Complied        10978     17.3
2                             Warning Issued         9062     14.3
3       Administrative complaint recommended         5022      7.9
4   Call Back - Admin. complaint recommended         2289      3.6
5                Emergency order recommended         2044      3.2
6       Call Back - Extension given, pending         2008      3.2
7          Emergency Order Callback Complied         1527      2.4
8      Emergency Order Callback Not Complied          960      1.5
9    Emergency Order Callback Time Extension          311      0.5
10                     Assigned to Inspector           54      0.1
11  Administrative determination recommended           14      0.0
12              Not available electronically           12      0.0
13        Admin. Complaint Callback Complied            8      0.0
14  Insp. Completed - Warning Given, Pending            5      0.0
15    Admin. Complaint Callback Not Complied            3      0.0
16                   Allegation Not Observed            3      0.0

In [44]:
chart4 = complaints.copy()

def simplify_disposition(x):
    x = str(x)

    if "No Further Action" in x:
        return "No further action"

    elif "Warning" in x:
        return "Warning issued"

    elif "Emergency order recommended" in x:
        return "Emergency order"

    elif "Admin" in x:
        return "Administrative complaint"

    elif "Call Back" in x or "Callback" in x or "Assigned to Inspector" in x:
        return "Follow-up required"

    else:
        return "Other"

chart4["Outcome"] = chart4["DISPOSITION"].apply(simplify_disposition)

chart4 = (
    chart4.groupby("Outcome", as_index=False)
    .size()
    .rename(columns={"size": "Inspections"})
)

chart4["Percent"] = (
    chart4["Inspections"]
    / chart4["Inspections"].sum()
    * 100
).round(1)

chart4 = chart4.sort_values("Percent", ascending=False)

chart4

                    Outcome  Inspections  Percent
3         No further action        29058     45.9
2        Follow-up required        15838     25.0
5            Warning issued         9067     14.3
0  Administrative complaint         7336     11.6
1           Emergency order         2044      3.2
4                     Other           15      0.0

In [45]:
chart4["Outcome"] = chart4["Outcome"].replace({
    "Follow-up required": "Follow-up inspection",
    "Emergency order": "Emergency closure recommended"
})

In [46]:
chart4.to_csv(
    "../data/processed/chart4_complaint_outcomes.csv",
    index=False
)